services:
  postgres:
    image: postgres:15
    container_name: BudaTrip-Postgres
    environment:
      POSTGRES_USER: BudaTrip
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: BudaTripDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
