services:
  postgres:
    image: postgres:15
    container_name: BT
    environment:
      POSTGRES_USER: romain
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bt_db
    ports:
      - "5432:5432"
    volumes:
      - ./.DockerVolume:/var/lib/postgresql/data
    restart: unless-stopped

